---
title: "Pointing to agent v.s Pointing to building"
author: "Tracy Sánchez"
date: "Última actualización: `r format(Sys.Date(), format = '%d %B %Y')`" 
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: tango
    toc_depth: 6
    mathjax: null
    css: doc.css # To set style to maximum in a separate file

---


```{r setup, include=FALSE}
# Set global chunk options for R Markdown output
knitr::opts_chunk$set(comment = NA)  # Removes all hashtags from output in HTML 

# Load required packages
library_packages <- c(
  "readr", "dlookr", "dplyr", "lme4", "car", "emmeans", "MASS", "jtools", 
  "lmerTest", "gmodels", "nlme", "multcompView", "ggplot2", "sjPlot", "sjstats"
)
lapply(library_packages, library, character.only = TRUE)

# Set options for emmeans
#emm_options(lmerTest.limit = 10000)
#emm_options(pbkrtest.limit = 10000)

# Not scientific notation
options(scipen=999)
```



```{r}
HumanA_Agent <- read.csv("/Volumes/TwoTeras/1_Experiment_2/Eye_Tracking/Pre_processed/Data_Sets/AgentData_Fixations_Wide.csv", sep =",")
unique(HumanA_Agent$SubjectID)
```

```{r}
#HumanA_Agent <- HumanA_Agent %>% dplyr::filter(!SubjectID %in% c(4580, 3540))
HumanA_Agent$ContextEffectf <-dplyr::recode(HumanA_Agent$Context, 
                                      False = -0.5, True= 0.5,
                                      .default = NaN)
HumanA_Agent$AgentPresence <-dplyr::recode(HumanA_Agent$AvatarPresenceCategory,
                                             Omitted = -0.5, Present= 0.5,
                                             .default = NaN)
HumanA_Agent$Agent_Action_level <-dplyr::recode(HumanA_Agent$AgentCategory,
                                             Passive = -0.5, Active= 0.5,
                                             .default = NaN)
HumanA_Agent$ContextEffectf <-factor(HumanA_Agent$ContextEffectf,levels= c(-0.5, 0.5), 
                               labels=c('Residential', 'Public')) 
HumanA_Agent$AgentPresencef <-factor(HumanA_Agent$AgentPresence,
                                levels= c(-0.5, 0.5), 
                                labels=c('Omitted', 'Displayed'))
HumanA_Agent$Agent_Action_levelf <-factor(HumanA_Agent$Agent_Action_level,
                                levels= c(-0.5, 0.5), 
                                labels=c('Passive', 'Active'))

```

```{r}
df <- HumanA_Agent %>% 
  filter(complete.cases(.))

p <- ggplot(df, aes(x = AbsolutError, fill = Agent_Action_levelf)) +
  
  geom_histogram(aes(group = Agent_Action_levelf), 
                 position = "identity", 
                 alpha = 0.5, 
                 binwidth = 10) +
  
  facet_grid(cols = vars(ContextEffectf)) +
  
  theme_bw()

# Print the plot
p
```

# Data descriptives
```{r}
MainVariables_Agent <- subset(HumanA_Agent, select = c(AbsolutError, RT))
summary(MainVariables_Agent)
```


```{r}
df_Agent = HumanA_Agent[complete.cases(HumanA_Agent),]

ggplot(df_Agent,aes(x=AbsolutError,group=Agent_Action_levelf,fill=Agent_Action_levelf))+
  geom_histogram(position="identity",alpha=0.5,binwidth=10)+  facet_grid(cols = vars(ContextEffectf))+theme_bw()
```
```{r}
TwoFactorTable_Agent <- HumanA_Agent %>% 
  group_by(ContextEffectf, Agent_Action_levelf)%>%
  summarise(AccuracyMean = mean(AbsolutError, na.rm = TRUE),
            n=n(),
            AccuracyStandardDev = sd(AbsolutError, na.rm = TRUE),
            RTMean = mean(RT, na.rm = TRUE),
            RTStandardDev = sd(RT, na.rm = TRUE))
TwoFactorTable_Agent
```

```{r }

TwoFactorTable_Agent <- HumanA_Agent %>% 
  group_by(ContextEffectf, Agent_Action_levelf)%>%
  summarise(AccuracyMean = mean(AbsolutError, na.rm = TRUE),
            n=n(),
            AccuracyStandardDev = sd(AbsolutError, na.rm = TRUE),
            RTMean = mean(RT, na.rm = TRUE),
            RTStandardDev = sd(RT, na.rm = TRUE))
library(tidyr)
TwoFactorTableUnite_Agent <- TwoFactorTable_Agent %>%
  unite("TwoFactor", ContextEffectf:Agent_Action_levelf, sep= " ", remove = F)
  
TwoFactorTableUnite_Agent <-  TwoFactorTableUnite_Agent %>%
  mutate( AccuracyStandardError=AccuracyStandardDev/sqrt(n)) %>%  
  mutate( AccuracyStandardIC=AccuracyStandardDev * qt((1-0.05)/2 + .5, n-1)) %>%
  mutate( RTStandardError=RTStandardDev/sqrt(n)) 
```


## Checking for the distribution of Absolut error
```{r warning = FALSE }
df_Agent = HumanA_Agent[complete.cases(HumanA_Agent),]
df_Agent$AbsolutErrorR <- round(df_Agent$AbsolutError, digits = 3)
qqp(df_Agent$AbsolutErrorR, "norm")
qqp(df_Agent$AbsolutErrorR, "lnorm")

```

## --- Assessing the need for a multilevel model ---


```{r}
# Model with only intercept
interceptOnly_Agent<-gls(AbsolutErrorR ~ 1, data = df_Agent, 
                    method = "ML")
# Add ID as random intercept
IDrandomInterceptOnly_Agent <-lmer(AbsolutErrorR ~ 1 + (1|SubjectID), data = df_Agent)
# Add both ID and Starting Position as random intercepts
TrialIDrandomIntercept_Agent <-lmer(AbsolutErrorR ~ 1 + (1|StartPointID) + (1|SubjectID), data = df_Agent)
cat("Including Id and starting position as random effects significantly improves the fit of the model\n")
```

```{r}
# Just behavioral
# No Eye-tracking
No_Eye_tracking <- update(TrialIDrandomIntercept_Agent, .~. + ContextEffectf*Agent_Action_levelf )
# Model summary
summary(No_Eye_tracking)
# Anova test for the model
Anova(No_Eye_tracking)
```
```{r}
# Load necessary libraries
library(lme4)
library(emmeans)

# Fit the linear mixed-effects model
model <- lmer(AbsolutError ~ (1 | SubjectID) + (1 | PointingTaskStartingLocations) + 
                ContextEffectf + Agent_Action_levelf + ContextEffectf:Agent_Action_levelf, 
              data = df)

# Calculate EMMeans for ContextEffectf, Agent_Action_levelf, and their interaction
emm_context <- emmeans(model, ~ ContextEffectf)
emm_agent <- emmeans(model, ~ Agent_Action_levelf)
emm_interaction <- emmeans(model, ~ ContextEffectf * Agent_Action_levelf)

# Print the EMMeans results
print(emm_context)
print(emm_agent)
print(emm_interaction)

# Calculate pairwise contrasts to see the differences
pairs_context <- pairs(emm_context)
pairs_agent <- pairs(emm_agent)
pairs_interaction <- pairs(emm_interaction)

# Print the pairwise contrasts results
print(pairs_context)
print(pairs_agent)
print(pairs_interaction)
```



```{r}
# Complete model with all predictors
Complete_model <- update(TrialIDrandomIntercept_Agent, 
                        . ~ . + Dwelling_Time_Building_Gaze + Dwelling_Time_Agent_Gaze +   ContextEffectf*Agent_Action_levelf)
# Model summary
summary(Complete_model)
```
```{r}
library(data.table)
model_df <- data.table(coef(summary(Complete_model)), keep.rownames = 'term')
write.csv(model_df, "/Volumes/TwoTeras/Resources/Complete_model_Agent.csv")
```





```{r}
library(glmmTMB)
library(sjPlot)
plot_model(TwofactorInteraction_Agent, type="re")
plot_model(TwofactorInteraction_Agent, type="est", legend_title = "Custom Legend Title")
plot_model(TwofactorInteraction_Agent, type="pred")
plot_model(TwofactorInteraction_Agent, type="int", mdrt.values = "quart")
```

```{r}
plot_model(TwofactorInteraction_Agent, show.values = TRUE, value.offset = .3, axis.labels = c("Location * Agent category","Agent category (Active vs Passive)","Location (Public vs. Residential) ", "Agent presence on the task stimuli"), title = "LMM predictor estimates for response time", colors="bw",  vline.color = "red")
```

```{r}
interceptOnly<-gls(AbsolutErrorR ~ 1, data = df_Agent, method="ML")
IDrandomIntercept <-lmer(AbsolutErrorR ~ 1 + (1|SubjectID), data = df_Agent)
PointingLocations <-lmer(AbsolutErrorR ~ 1 + (1|StartPointID) + (1|SubjectID), data = df_Agent)
anova( IDrandomIntercept, PointingLocations)
```

```{r}
TwofactorInteraction_Agent <-update(PointingLocations, .~. +  Dwelling_Time_Building_Gaze+Dwelling_Time_Agent_Gaze)
summary(TwofactorInteraction_Agent)
Anova(TwofactorInteraction_Agent)
```

```{r}
plot_model(TwofactorInteraction_Agent, show.values = TRUE, value.offset = .3, colors="bw",  vline.color = "red")
tab_model(TwofactorInteraction_Agent)
```

```{r}
linear_model <- lm(AbsolutError ~ Dwelling_Time_Building_Gaze+Dwelling_Time_Agent_Gaze + ContextEffectf*Agent_Action_levelf, data=df_Agent)
Complete_model <-update(PointingLocations, .~. + Dwelling_Time_Building_Gaze+Dwelling_Time_Agent_Gaze + ContextEffectf*Agent_Action_levelf)
Complete_model_NOMATCH <-update(PointingLocations, .~. + Dwelling_Time_Building_Gaze+Dwelling_Time_Agent_Gaze + ContextEffectf*Agent_Action_levelf)
summary(Complete_model)
Anova(Complete_model)
```